load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tile",
    hdrs = ["tile.h",],
    deps = ["//lib/SFML-2.5.1:sfml_lib"],
)

cc_library(
    name = "agent",
    hdrs = ["agent.h",],
    deps = ["//lib/SFML-2.5.1:sfml_lib"],
)

cc_library(
    name = "utils",
    hdrs = ["utils.h",],
    deps = ["//lib/SFML-2.5.1:sfml_lib"],
)